[project]
name = 'Swarm-Intelligence-Protocol'
description = ''
authors = []
telemetry = true
cache_dir = '.\.cache'
requirements = []
[contracts.collective-decision-engine]
path = 'contracts/collective-decision-engine.clar'
clarity_version = 3
epoch = '3.2'

[contracts.human-ai-integration-layer]
path = 'contracts/human-ai-integration-layer.clar'
clarity_version = 3
epoch = '3.2'

[contracts.intelligence-contribution-rewards]
path = 'contracts/intelligence-contribution-rewards.clar'
clarity_version = 3
epoch = 'latest'
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false

[repl.remote_data]
enabled = false
api_url = 'https://api.hiro.so'
